// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortDash.Target.Data;

namespace ShortDash.Target.Migrations
{
    [DbContext(typeof(TargetApplicationDbContext))]
    [Migration("20201212014429_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ShortDash.Core.Data.ConfigurationSection", b =>
                {
                    b.Property<string>("ConfigurationSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigurationSectionId");

                    b.ToTable("ConfigurationSections");
                });
#pragma warning restore 612, 618
        }
    }
}
