name: ShortDash-CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.15.5'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install build dependencies
      run: sudo apt-get install gcc libgtk-3-dev libappindicator3-dev

    - name: Build and Test
      shell: bash
      run: |
        chmod +x build.sh
        ./build.sh -m CI -b ${GITHUB_RUN_NUMBER}

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.15.5'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build and Test
      shell: bash
      run: |
        chmod +x build.sh
        ./build.sh -m CI -b ${GITHUB_RUN_NUMBER}

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.15.5'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build and Test
      shell: powershell
      run: .\build.ps1 -m CI -b $Env:GITHUB_RUN_NUMBER