name: ShortDash-Release

on:
  release:
    types: [published]

jobs:
  release-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.5'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install build dependencies
      run: sudo apt-get install gcc libgtk-3-dev libappindicator3-dev

    - name: Publish binaries
      shell: bash
      run: |
        chmod +x build.sh
        ./build.sh -m RELEASE -b ${GITHUB_RUN_NUMBER} -r "${GITHUB_REF}"

    - name: Upload binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ShortDash-linux-arm64.tar.gz
          bin/ShortDash-linux-x64.tar.gz
          bin/ShortDash-Server-linux-x64.deb
          bin/ShortDash-Target-linux-x64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.5'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Publish binaries
      shell: bash
      run: |
        chmod +x build.sh
        ./build.sh -m RELEASE -b ${GITHUB_RUN_NUMBER} -r "${GITHUB_REF}"

    - name: Upload binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ShortDash-osx-x64.tar.gz
          bin/ShortDash-osx-x64.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.5'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Publish binaries
      shell: powershell
      run: .\build.ps1 -m RELEASE -b $Env:GITHUB_RUN_NUMBER -r "$Env:GITHUB_REF"

    - name: Upload binaries
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ShortDash-win-x64.zip
          bin/ShortDash-win-x64-setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}