name: ShortDash-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-cross-platform:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build and Test
      shell: bash
      run: |
        chmod +x build.sh
        ./build.sh -m CI -b ${GITHUB_RUN_NUMBER}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ShortDash-CI-cross-platform
        path: bin/ShortDash-CI-cross-platform/**

  build-launcher-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build and Test
      shell: powershell
      run: .\build.ps1 -m CI -b $Env:GITHUB_RUN_NUMBER

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ShortDash-CI-launcher-win-x64
        path: bin/ShortDash-CI-win-x64/**